[board]
padding_pc = 0.12
edge_padding = 1.5
piece_scale = 0.004
taken_piece_scale = 0.001

[white_piece_offsets]
pawn = { x = 0.0055, y = 0 }
bishop = { x = 0.0015, y = 0 }
knight = { x = 0.0015, y = 0 }
rook = { x = 0.007, y = -0.003 }
queen = { x = 0, y = 0 }
king = { x = 0, y = 0 }

[black_piece_offsets]
pawn = { x = 0.005, y = 0 }
bishop = { x = 0.002, y = 0 }
knight = { x = 0.002, y = 0 }
rook = { x = 0.0075, y = -0.005 }
queen = { x = 0.003, y = -0.001 }
king = { x = 0, y = 0 }

[button]
color = { r = 200, g = 200, b = 200, a = 120 }
hover_color = { r = 255, g = 255, b = 255, a = 150 }
outline_color = { r = 200, g = 200, b = 200, a = 255 }
width = 4

[piece_selection]
color = { r = 0, g = 255, b = 0, a = 255 }
width = 5

[taken_piece_offsets]
x = 0.08
y = 0.15
y_factor = 0.04
